// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: example_grpc.proto

#include "example_grpc.pb.h"
#include "example_grpc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace examplegrpc {

static const char* ExampleGrpc_method_names[] = {
  "/examplegrpc.ExampleGrpc/getMyName",
};

std::unique_ptr< ExampleGrpc::Stub> ExampleGrpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ExampleGrpc::Stub> stub(new ExampleGrpc::Stub(channel, options));
  return stub;
}

ExampleGrpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_getMyName_(ExampleGrpc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ExampleGrpc::Stub::getMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::examplegrpc::NameResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::examplegrpc::NameRequest, ::examplegrpc::NameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getMyName_, context, request, response);
}

void ExampleGrpc::Stub::async::getMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest* request, ::examplegrpc::NameResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::examplegrpc::NameRequest, ::examplegrpc::NameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getMyName_, context, request, response, std::move(f));
}

void ExampleGrpc::Stub::async::getMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest* request, ::examplegrpc::NameResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getMyName_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::examplegrpc::NameResponse>* ExampleGrpc::Stub::PrepareAsyncgetMyNameRaw(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::examplegrpc::NameResponse, ::examplegrpc::NameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getMyName_, context, request);
}

::grpc::ClientAsyncResponseReader< ::examplegrpc::NameResponse>* ExampleGrpc::Stub::AsyncgetMyNameRaw(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetMyNameRaw(context, request, cq);
  result->StartCall();
  return result;
}

ExampleGrpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ExampleGrpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ExampleGrpc::Service, ::examplegrpc::NameRequest, ::examplegrpc::NameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ExampleGrpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::examplegrpc::NameRequest* req,
             ::examplegrpc::NameResponse* resp) {
               return service->getMyName(ctx, req, resp);
             }, this)));
}

ExampleGrpc::Service::~Service() {
}

::grpc::Status ExampleGrpc::Service::getMyName(::grpc::ServerContext* context, const ::examplegrpc::NameRequest* request, ::examplegrpc::NameResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace examplegrpc
#include <grpcpp/ports_undef.inc>

