// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: example_grpc.proto
#ifndef GRPC_example_5fgrpc_2eproto__INCLUDED
#define GRPC_example_5fgrpc_2eproto__INCLUDED

#include "example_grpc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace examplegrpc {

// Interface exported by the server
class ExampleGrpc final {
 public:
  static constexpr char const* service_full_name() {
    return "examplegrpc.ExampleGrpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // A simple RPC.
    // Returns the name of the client that invoked the RPC.
    virtual ::grpc::Status getMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::examplegrpc::NameResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::examplegrpc::NameResponse>> AsyncgetMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::examplegrpc::NameResponse>>(AsyncgetMyNameRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::examplegrpc::NameResponse>> PrepareAsyncgetMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::examplegrpc::NameResponse>>(PrepareAsyncgetMyNameRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // A simple RPC.
      // Returns the name of the client that invoked the RPC.
      virtual void getMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest* request, ::examplegrpc::NameResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest* request, ::examplegrpc::NameResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::examplegrpc::NameResponse>* AsyncgetMyNameRaw(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::examplegrpc::NameResponse>* PrepareAsyncgetMyNameRaw(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status getMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::examplegrpc::NameResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::examplegrpc::NameResponse>> AsyncgetMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::examplegrpc::NameResponse>>(AsyncgetMyNameRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::examplegrpc::NameResponse>> PrepareAsyncgetMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::examplegrpc::NameResponse>>(PrepareAsyncgetMyNameRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void getMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest* request, ::examplegrpc::NameResponse* response, std::function<void(::grpc::Status)>) override;
      void getMyName(::grpc::ClientContext* context, const ::examplegrpc::NameRequest* request, ::examplegrpc::NameResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::examplegrpc::NameResponse>* AsyncgetMyNameRaw(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::examplegrpc::NameResponse>* PrepareAsyncgetMyNameRaw(::grpc::ClientContext* context, const ::examplegrpc::NameRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getMyName_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // A simple RPC.
    // Returns the name of the client that invoked the RPC.
    virtual ::grpc::Status getMyName(::grpc::ServerContext* context, const ::examplegrpc::NameRequest* request, ::examplegrpc::NameResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getMyName : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getMyName() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getMyName() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getMyName(::grpc::ServerContext* /*context*/, const ::examplegrpc::NameRequest* /*request*/, ::examplegrpc::NameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetMyName(::grpc::ServerContext* context, ::examplegrpc::NameRequest* request, ::grpc::ServerAsyncResponseWriter< ::examplegrpc::NameResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getMyName<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_getMyName : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_getMyName() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::examplegrpc::NameRequest, ::examplegrpc::NameResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::examplegrpc::NameRequest* request, ::examplegrpc::NameResponse* response) { return this->getMyName(context, request, response); }));}
    void SetMessageAllocatorFor_getMyName(
        ::grpc::MessageAllocator< ::examplegrpc::NameRequest, ::examplegrpc::NameResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::examplegrpc::NameRequest, ::examplegrpc::NameResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_getMyName() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getMyName(::grpc::ServerContext* /*context*/, const ::examplegrpc::NameRequest* /*request*/, ::examplegrpc::NameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getMyName(
      ::grpc::CallbackServerContext* /*context*/, const ::examplegrpc::NameRequest* /*request*/, ::examplegrpc::NameResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_getMyName<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getMyName : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getMyName() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getMyName() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getMyName(::grpc::ServerContext* /*context*/, const ::examplegrpc::NameRequest* /*request*/, ::examplegrpc::NameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getMyName : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getMyName() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getMyName() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getMyName(::grpc::ServerContext* /*context*/, const ::examplegrpc::NameRequest* /*request*/, ::examplegrpc::NameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetMyName(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_getMyName : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_getMyName() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getMyName(context, request, response); }));
    }
    ~WithRawCallbackMethod_getMyName() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getMyName(::grpc::ServerContext* /*context*/, const ::examplegrpc::NameRequest* /*request*/, ::examplegrpc::NameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getMyName(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getMyName : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getMyName() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::examplegrpc::NameRequest, ::examplegrpc::NameResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::examplegrpc::NameRequest, ::examplegrpc::NameResponse>* streamer) {
                       return this->StreamedgetMyName(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getMyName() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getMyName(::grpc::ServerContext* /*context*/, const ::examplegrpc::NameRequest* /*request*/, ::examplegrpc::NameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetMyName(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::examplegrpc::NameRequest,::examplegrpc::NameResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getMyName<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getMyName<Service > StreamedService;
};

}  // namespace examplegrpc


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_example_5fgrpc_2eproto__INCLUDED
